services:
#  node:
#    container_name: nest_micro_dev_node
#    build:
#      context: .
#      dockerfile: .docker/compose/node/Dockerfile.local
#    extends:
#      file: .docker/compose/node/node.yml
#      service: node
#    ports:
#      -
#    volumes:
#      - ${PWD}:/work
#    depends_on:
#      db:
#        condition: service_healthy
#    networks:
#      - nest-micro-dev-network
#    env_file:
#      - .env

  db:
    container_name: nest_micro_dev_db
    extends:
      file: .docker/compose/postgresql/postgresql.yml
      service: postgresql
    ports:
      - '5554:5432'
    volumes:
      - ${PWD}/.docker/volumes/pg_data:/var/lib/postgresql/data
    networks:
      - nest-micro-dev-network
    environment:
      POSTGRES_USER: ${DEFAULT_PG_USER}
      POSTGRES_PASSWORD: ${DEFAULT_PG_PASSWORD}
      POSTGRES_DB: ${DEFAULT_PG_DATABASE}
    env_file:
      - .env

  redis:
    container_name: nest_micro_dev_redis
    extends:
      file: .docker/compose/redis/redis.yml
      service: redis
    ports:
      - '6574:6379'
    networks:
      - nest-micro-dev-network
    volumes:
      - ${PWD}/.docker/volumes/redis_data:/data
    command: redis-server --appendonly yes --dir /data

  redisinsight:
    container_name: nest_micro_dev_redisinsight
    extends:
      file: .docker/compose/redis/redis.yml
      service: redisinsight
    ports:
      - '6575:5540'
    networks:
      - nest-micro-dev-network
    volumes:
      - ${PWD}/.docker/volumes/redisinsight_data:/db

#volumes:
#  pgdata:
#  redisdata:

networks:
  nest-micro-dev-network:
    driver: bridge